create table zones (
    id bigint generated by default as identity primary key,
    center_lat double precision not null,
    center_lon double precision not null,
    width double precision not null,
    height double precision not null,
    name varchar(100),
    description text
);
