create table buildings (
    id bigint generated by default as identity primary key,
    zone_id bigint not null references zones(id),
    latitude double precision not null,
    longitude double precision not null,
    name varchar(100)
);