create table hidden_pokemons (
    id bigint generated by default as identity primary key,
    pokemon_id bigint not null references pokemons(id),
    building_id bigint not null unique references buildings(id),
    spawn_time timestamp not null,
    despawn_time timestamp not null,
    is_caught boolean default false not null
);