create table pokemon_catches (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    spawn_id bigint not null references hidden_pokemons(id),
    pokeball_type varchar(50) not null,
    catch_time timestamp not null,
    success boolean not null,
    xp_earned integer not null
);