create table user_pokemons (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    pokemon_id bigint not null references pokemons(id),
    catch_id bigint references pokemon_catches(id),
    caught_at timestamp not null,
    nickname varchar(100)
);